# Generated by Django 4.1.5 on 2023-02-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation',
            new_name='variation_category',
        ),
    ]
