# Generated by Django 4.1.5 on 2023-01-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catergory_name',
            new_name='category_name',
        ),
    ]
